#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAES_Maxime_projet_BD.DataAccess.DataObject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Voiture")]
	public partial class AchatVenteFinancesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertAchatVenteVoiture(AchatVenteVoiture instance);
    partial void UpdateAchatVenteVoiture(AchatVenteVoiture instance);
    partial void DeleteAchatVenteVoiture(AchatVenteVoiture instance);
    #endregion
		
		public AchatVenteFinancesDataContext() : 
				base(global::MAES_Maxime_projet_BD.Properties.Settings.Default.BD_VoitureConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public AchatVenteFinancesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AchatVenteFinancesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AchatVenteFinancesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AchatVenteFinancesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AchatVenteVoiture> AchatVenteVoiture
		{
			get
			{
				return this.GetTable<AchatVenteVoiture>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AchatVenteVoiture")]
	public partial class AchatVenteVoiture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idOperation;
		
		private int _idVoiture;
		
		private int _idClient;
		
		private int _prixOperation;
		
		private System.DateTime _dateOperation;
		
		private int _idPaiement;
		
		private string _typeOperation;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidOperationChanging(int value);
    partial void OnidOperationChanged();
    partial void OnidVoitureChanging(int value);
    partial void OnidVoitureChanged();
    partial void OnidClientChanging(int value);
    partial void OnidClientChanged();
    partial void OnprixOperationChanging(int value);
    partial void OnprixOperationChanged();
    partial void OndateOperationChanging(System.DateTime value);
    partial void OndateOperationChanged();
    partial void OnidPaiementChanging(int value);
    partial void OnidPaiementChanged();
    partial void OntypeOperationChanging(string value);
    partial void OntypeOperationChanged();
    #endregion
		
		public AchatVenteVoiture()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOperation", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idOperation
		{
			get
			{
				return this._idOperation;
			}
			set
			{
				if ((this._idOperation != value))
				{
					this.OnidOperationChanging(value);
					this.SendPropertyChanging();
					this._idOperation = value;
					this.SendPropertyChanged("idOperation");
					this.OnidOperationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVoiture", DbType="Int NOT NULL")]
		public int idVoiture
		{
			get
			{
				return this._idVoiture;
			}
			set
			{
				if ((this._idVoiture != value))
				{
					this.OnidVoitureChanging(value);
					this.SendPropertyChanging();
					this._idVoiture = value;
					this.SendPropertyChanged("idVoiture");
					this.OnidVoitureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClient", DbType="Int NOT NULL")]
		public int idClient
		{
			get
			{
				return this._idClient;
			}
			set
			{
				if ((this._idClient != value))
				{
					this.OnidClientChanging(value);
					this.SendPropertyChanging();
					this._idClient = value;
					this.SendPropertyChanged("idClient");
					this.OnidClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prixOperation", DbType="Int NOT NULL")]
		public int prixOperation
		{
			get
			{
				return this._prixOperation;
			}
			set
			{
				if ((this._prixOperation != value))
				{
					this.OnprixOperationChanging(value);
					this.SendPropertyChanging();
					this._prixOperation = value;
					this.SendPropertyChanged("prixOperation");
					this.OnprixOperationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOperation", DbType="DateTime NOT NULL")]
		public System.DateTime dateOperation
		{
			get
			{
				return this._dateOperation;
			}
			set
			{
				if ((this._dateOperation != value))
				{
					this.OndateOperationChanging(value);
					this.SendPropertyChanging();
					this._dateOperation = value;
					this.SendPropertyChanged("dateOperation");
					this.OndateOperationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaiement", DbType="Int NOT NULL")]
		public int idPaiement
		{
			get
			{
				return this._idPaiement;
			}
			set
			{
				if ((this._idPaiement != value))
				{
					this.OnidPaiementChanging(value);
					this.SendPropertyChanging();
					this._idPaiement = value;
					this.SendPropertyChanged("idPaiement");
					this.OnidPaiementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeOperation", DbType="VarChar(255)")]
		public string typeOperation
		{
			get
			{
				return this._typeOperation;
			}
			set
			{
				if ((this._typeOperation != value))
				{
					this.OntypeOperationChanging(value);
					this.SendPropertyChanging();
					this._typeOperation = value;
					this.SendPropertyChanged("typeOperation");
					this.OntypeOperationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
