<?xml version="1.0" encoding="utf-8"?><Database Name="BD_Voiture" Class="AchatVenteFinancesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Maesm\Desktop\MAES_Maxime_projet_BD_V2\BD\BD_Voiture.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="MAES_Maxime_projet_BD.Properties.Settings" SettingsPropertyName="BD_VoitureConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AchatVenteVoiture" Member="AchatVenteVoiture">
    <Type Name="AchatVenteVoiture">
      <Column Name="idOperation" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idVoiture" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idClient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prixOperation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateOperation" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idPaiement" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="typeOperation" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>