#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAES_Maxime_projet_BD.DataAccess.DataObject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Voiture")]
	public partial class MarquesAchatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertMarqueVoiture(MarqueVoiture instance);
    partial void UpdateMarqueVoiture(MarqueVoiture instance);
    partial void DeleteMarqueVoiture(MarqueVoiture instance);
    #endregion
		
		public MarquesAchatDataContext() : 
				base(global::MAES_Maxime_projet_BD.Properties.Settings.Default.BD_VoitureConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public MarquesAchatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarquesAchatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarquesAchatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarquesAchatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MarqueVoiture> MarqueVoiture
		{
			get
			{
				return this.GetTable<MarqueVoiture>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MarqueVoiture")]
	public partial class MarqueVoiture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMarque;
		
		private string _nomMarque;
		
		private string _paysMarque;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMarqueChanging(int value);
    partial void OnidMarqueChanged();
    partial void OnnomMarqueChanging(string value);
    partial void OnnomMarqueChanged();
    partial void OnpaysMarqueChanging(string value);
    partial void OnpaysMarqueChanged();
    #endregion
		
		public MarqueVoiture()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMarque", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMarque
		{
			get
			{
				return this._idMarque;
			}
			set
			{
				if ((this._idMarque != value))
				{
					this.OnidMarqueChanging(value);
					this.SendPropertyChanging();
					this._idMarque = value;
					this.SendPropertyChanged("idMarque");
					this.OnidMarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomMarque", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nomMarque
		{
			get
			{
				return this._nomMarque;
			}
			set
			{
				if ((this._nomMarque != value))
				{
					this.OnnomMarqueChanging(value);
					this.SendPropertyChanging();
					this._nomMarque = value;
					this.SendPropertyChanged("nomMarque");
					this.OnnomMarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paysMarque", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string paysMarque
		{
			get
			{
				return this._paysMarque;
			}
			set
			{
				if ((this._paysMarque != value))
				{
					this.OnpaysMarqueChanging(value);
					this.SendPropertyChanging();
					this._paysMarque = value;
					this.SendPropertyChanged("paysMarque");
					this.OnpaysMarqueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
