<?xml version="1.0" encoding="utf-8"?><Database Name="BD_Voiture" Class="PaiementAchatDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Maesm\Desktop\MAES_Maxime_projet_BD_V2\BD\BD_Voiture.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="MAES_Maxime_projet_BD.Properties.Settings" SettingsPropertyName="BD_VoitureConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PaiementVoiture" Member="PaiementVoiture">
    <Type Name="PaiementVoiture">
      <Column Name="idPaiement" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomPaiement" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>