#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAES_Maxime_projet_BD.DataAccess.DataObject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Voiture")]
	public partial class StockVoitureDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertStockVoiture(StockVoiture instance);
    partial void UpdateStockVoiture(StockVoiture instance);
    partial void DeleteStockVoiture(StockVoiture instance);
    #endregion
		
		public StockVoitureDataContext() : 
				base(global::MAES_Maxime_projet_BD.Properties.Settings.Default.BD_VoitureConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public StockVoitureDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StockVoitureDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StockVoitureDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StockVoitureDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StockVoiture> StockVoiture
		{
			get
			{
				return this.GetTable<StockVoiture>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StockVoiture")]
	public partial class StockVoiture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idVoiture;
		
		private int _idMarque;
		
		private int _idModele;
		
		private int _idCategorie;
		
		private System.Nullable<int> _anneeFabrication;
		
		private System.Nullable<int> _idCarburant;
		
		private System.Nullable<int> _idCouleur;
		
		private System.Nullable<int> _kilometrage;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidVoitureChanging(int value);
    partial void OnidVoitureChanged();
    partial void OnidMarqueChanging(int value);
    partial void OnidMarqueChanged();
    partial void OnidModeleChanging(int value);
    partial void OnidModeleChanged();
    partial void OnidCategorieChanging(int value);
    partial void OnidCategorieChanged();
    partial void OnanneeFabricationChanging(System.Nullable<int> value);
    partial void OnanneeFabricationChanged();
    partial void OnidCarburantChanging(System.Nullable<int> value);
    partial void OnidCarburantChanged();
    partial void OnidCouleurChanging(System.Nullable<int> value);
    partial void OnidCouleurChanged();
    partial void OnkilometrageChanging(System.Nullable<int> value);
    partial void OnkilometrageChanged();
    #endregion
		
		public StockVoiture()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVoiture", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idVoiture
		{
			get
			{
				return this._idVoiture;
			}
			set
			{
				if ((this._idVoiture != value))
				{
					this.OnidVoitureChanging(value);
					this.SendPropertyChanging();
					this._idVoiture = value;
					this.SendPropertyChanged("idVoiture");
					this.OnidVoitureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMarque", DbType="Int NOT NULL")]
		public int idMarque
		{
			get
			{
				return this._idMarque;
			}
			set
			{
				if ((this._idMarque != value))
				{
					this.OnidMarqueChanging(value);
					this.SendPropertyChanging();
					this._idMarque = value;
					this.SendPropertyChanged("idMarque");
					this.OnidMarqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idModele", DbType="Int NOT NULL")]
		public int idModele
		{
			get
			{
				return this._idModele;
			}
			set
			{
				if ((this._idModele != value))
				{
					this.OnidModeleChanging(value);
					this.SendPropertyChanging();
					this._idModele = value;
					this.SendPropertyChanged("idModele");
					this.OnidModeleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategorie", DbType="Int NOT NULL")]
		public int idCategorie
		{
			get
			{
				return this._idCategorie;
			}
			set
			{
				if ((this._idCategorie != value))
				{
					this.OnidCategorieChanging(value);
					this.SendPropertyChanging();
					this._idCategorie = value;
					this.SendPropertyChanged("idCategorie");
					this.OnidCategorieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anneeFabrication", DbType="Int")]
		public System.Nullable<int> anneeFabrication
		{
			get
			{
				return this._anneeFabrication;
			}
			set
			{
				if ((this._anneeFabrication != value))
				{
					this.OnanneeFabricationChanging(value);
					this.SendPropertyChanging();
					this._anneeFabrication = value;
					this.SendPropertyChanged("anneeFabrication");
					this.OnanneeFabricationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarburant", DbType="Int")]
		public System.Nullable<int> idCarburant
		{
			get
			{
				return this._idCarburant;
			}
			set
			{
				if ((this._idCarburant != value))
				{
					this.OnidCarburantChanging(value);
					this.SendPropertyChanging();
					this._idCarburant = value;
					this.SendPropertyChanged("idCarburant");
					this.OnidCarburantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCouleur", DbType="Int")]
		public System.Nullable<int> idCouleur
		{
			get
			{
				return this._idCouleur;
			}
			set
			{
				if ((this._idCouleur != value))
				{
					this.OnidCouleurChanging(value);
					this.SendPropertyChanging();
					this._idCouleur = value;
					this.SendPropertyChanged("idCouleur");
					this.OnidCouleurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kilometrage", DbType="Int")]
		public System.Nullable<int> kilometrage
		{
			get
			{
				return this._kilometrage;
			}
			set
			{
				if ((this._kilometrage != value))
				{
					this.OnkilometrageChanging(value);
					this.SendPropertyChanging();
					this._kilometrage = value;
					this.SendPropertyChanged("kilometrage");
					this.OnkilometrageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
